# Generated by Django 4.1.1 on 2022-09-21 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.freelancer'),
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.ManyToManyField(to='users.category'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='freelancer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='users.freelancer'),
        ),
        migrations.AddField(
            model_name='order',
            name='promotion',
            field=models.ManyToManyField(blank=True, to='orders.promotion'),
        ),
        migrations.AddField(
            model_name='order',
            name='responses',
            field=models.ManyToManyField(to='orders.response'),
        ),
        migrations.AddField(
            model_name='order',
            name='reward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.reward'),
        ),
        migrations.AddField(
            model_name='order',
            name='skills',
            field=models.ManyToManyField(to='users.skill'),
        ),
    ]
